version: '3.5'

services:

  database:
    image: postgres:12
    container_name: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=Waitless
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      #- ./database/initial_base.sql:/docker-entrypoint-initdb.d/initial_base.sql

  flask-api:
    container_name: flask-servers
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./server/:/var/www/server
    depends_on:
      - "database"

  client:
    image: node:12
    container_name: react-app
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - "flask-api"
    restart: always
